### ISSUE TITLE
Cannot install lense_python in PyCharm

### ISSUE THREAD

**Issue by markus-zhang** [lensesio/lenses-python#28]
Hi experts,

I'm using Python 3.8 and PyCharm, but when I install lenses_python it failed. 
Error message says: _configtest.c(7): error C2143: syntax error: missing ';' before 'volatile'

I digged a bit into the full error message:
Running setup.py install for numpy: finished with status 'error', it seems that I cannot install 1.13.1 (tried to install by myself and failed). Is there a way to change to a newer version of Numpy? Thanks!

**Comment by ulfox** [comment]
Hi @markus-zhang this issue should be fixed with lensesPy branch. You can experiment with that branch or wait for the PR to be accepted.

Please read the installation description since it is different from the master branch

**Comment by ulfox** [comment]
I am closing this issue. Pandas has been removed as a dependency from latest update.

Please clone the repo, then
to build run:
`python3 setup.py sdist bdist_wheel`
and to install run
`pip3 install -U dist/lensesio-3.0.0-py3-none-any.whl`
