### ISSUE TITLE
Provide PyPI (pip) installable package

### ISSUE THREAD

**Issue by montsamu** [lensesio/lenses-python#49]
Unfortunately some Windows environments have issues (likely underlying with virtualenv/git) installing from a "git+ssh" URL. Can the team please provide an officially maintained PyPI (pip) installable package for lenses?

**Comment by montsamu** [comment]
Actually, it looks more like an "update" rather than "provide" as there is a 2.2 release from 2018:

https://pypi.org/project/lenses_python/

**Comment by montsamu** [comment]
Hello, I was wondering about an update for this.

**Comment by ulfox** [comment]
@montsamu hi,

We have released lenses 4.0.0. You can get it with 

`pip install lensesio==4.0.0`

**Comment by ulfox** [comment]
This is considered resolved and is closing.

**Comment by montsamu** [comment]
Thank you -- so far so good with 4.0.
