### ISSUE TITLE
Version of requests is pinned to 2.22.0

### ISSUE THREAD

**Issue by montsamu** [lensesio/lenses-python#50]
https://github.com/lensesio/lenses-python/blob/9224dad23e29789d3857e0a3fc5b563656143e25/setup.py#L89

Is there a (good) reason that lensesio-4.0.0 is pinned to requests version 2.22.0? This causes various requirements conflicts in projects which want to use 23, 24, or 25.

**Comment by ulfox** [comment]
@montsamu version 2.22.0 is the current tested version. We need to test newer request version before we update

**Comment by ulfox** [comment]
@montsamu we updated the request lib to v2.25.1. Please let us know if this works for you

**Comment by ulfox** [comment]
I am closing this issue for now as resolved. Lensesio lib with request version 2.25.1 can be found in the master and release/4.0 branches or via using pip3 install lensesio==4.0.1
