### ISSUE TITLE
Need to be able to pass more ssl options into websocket connection

### ISSUE THREAD

**Issue by montsamu** [lensesio/lenses-python#55]
Currently, we can only pass ssl_verify through lensesio.lenses.main down through to

https://github.com/lensesio/lenses-python/blob/master/lensesio/data/sql.py

And from there into websocket.create_connection:

        if self.verify_cert:
            conn = websocket.create_connection(
                self.lenses_exec_sql_endpoint
            )
        else:
            conn = websocket.create_connection(
                self.lenses_exec_sql_endpoint,
                sslopt={"cert_reqs": ssl.CERT_NONE}
            )

Unfortunately my deployment requires additional sslopt for websocket.create_connection, namely:

    check_hostname=False

    ssl_version=ssl.PROTOCOL_TLSv1_2

I propose that lenses.main as it exists be extended:

    def __init__(
            self,
            auth_type="basic",
            url=None,
            username=None,
            password=None,
            krb_service=None,
            service_account=None,
            verify_cert=True):

To:

    def __init__(
            self,
            auth_type="basic",
            url=None,
            username=None,
            password=None,
            krb_service=None,
            service_account=None,
            verify_cert=True,
            ssl_options={}):

As well as SQLExec.__init__, to change:

    def __init__(self, active_threads, verify_cert=True)

To:

    def __init__(self, active_threads, ssl_options={})

And accordingly pass these sslopts "as-is" into the websocket.create_connection call.

I am happy to work up and create a pull request if needed. Currently I am monkeypatching websocket prior to importing lenses:

    # monkeypatch websocket tls
    import ssl, websocket
    _websocket_create_connection = websocket.create_connection
    def _create_connection(url, timeout=None, class_=websocket.WebSocket, **options):
        _ssl_options = options.get("sslopt", {})
        _ssl_options = dict(_ssl_options, check_hostname=False, ssl_version=ssl.PROTOCOL_TLSv1_2)
        _options = dict(options, sslopt=_ssl_options)
        return _websocket_create_connection(url, timeout, class_, **_options)
    websocket.create_connection = _create_connection
    # end monkeypatch websocket tls

And while this is working is (obviously) far from ideal.

**Comment by montsamu** [comment]
Wanted to update this issue: beyond more SSL options, we also need to add a cookie to pass into websocket create_connection. The current monkeypatch looks more like this:

    _options = dict(options, sslopt=_ssl_options, header=["Cookie: AWSALB=CookieValue"])

So probably what the real "fix" looks like is letting us pass any options we want down into create_connection.

**Comment by andmarios** [comment]
Hello @montsamu. I am sorry, but this library has been abandoned for quite some time now and hasn't followed the development of the Lenses REST API.

I will close this issue as we are going to archive the repository. I apologize for the inconvenience both this action and the delay of communication may have caused you.
