### ISSUE TITLE
Lenses client should not call exit()

### ISSUE THREAD

**Issue by montsamu** [lensesio/lenses-python#56]
There are some paths in the client which can result in terminating the entire python application, e.g.

    if self.ConnectionValidation() == 1:
        print("Could not login to lenses...")
        exit(1)

This should raise an exception, not exit the entire python application. Throughout the client, please replace sys.exit() calls with appropriate exceptions.

**Comment by montsamu** [comment]
Since this still isn't merged and published in a new package, here is the local monkeypatch we are using in case it is helpful to others:
```

import lensesio.lenses

# monkeypatch lenses.exit to raise exception
def lenses_exit(x): raise Exception(f"lenses exception sys exit: {x}")
lensesio.lenses.exit = lenses_exit
# end monkeypatch
```

**Comment by andmarios** [comment]
Hello @montsamu. I am sorry, but this library has been abandoned for quite some time now and hasn't followed the development of the Lenses REST API.

I will close this issue as we are going to archive the repository. I apologize for the inconvenience both this action and the delay of communication may have caused you.
