### ISSUE TITLE
lensesio basic auth does not observe load balancer cookies

### ISSUE THREAD

**Issue by montsamu** [lensesio/lenses-python#57]
For high availability deployment of lenses we have multiple instances behind an ALB. However, the login/auth calls can sometimes go to different instances, where the second instance does not know about the token credential from the login call to the first instance.

Here is a monkeypatch we are using locally for this issue:

```
# monkeypatch lensesio.core.basic_auth
from requests import post, get
from json import dumps
import lensesio.core.basic_auth
def _connect(self):
        if None not in (
            self.payload['user'],
            self.payload['password']
        ):

            self.response = post(
                self.login_url,
                data=dumps(self.payload),
                headers=self.default_headers,
                verify=self.verify_cert
            )

            self.token = self.response.text
            if 'AWSALB' in self.response.cookies:
                self.alb_cookie = self.response.cookies['AWSALB']
            else:
                self.alb_cookie = None
        else:
            self.token = 'INVALID'

        self.active_headers = {
            'Content-Type': 'application/json',
            'Accept': 'application/json, text/plain',
            'X-Kafka-Lenses-Token': self.token
        }
        if self.alb_cookie:
            self.active_cookies = {"AWSALB": self.alb_cookie}
        else:
            self.active_cookies = {}

def _UserInfo(self):
        response = get(
            self.auth_url,
            headers=self.active_headers,
            cookies=self.active_cookies,
            verify=self.verify_cert
        )
        if response.status_code in [200, 201, 202, 203]:
            self.userInfo = response.json()
        else:
            self.userInfo = response.text
        return self.userInfo

lensesio.core.basic_auth.Basic.connect = _connect
lensesio.core.basic_auth.Basic.UserInfo = _UserInfo
# end monkeypatch lensesio.core.basic_auth

```

**Comment by montsamu** [comment]
OK, after some further testing, the first portion of the issue may not actually be needed -- use of json=self.payload instead of data=dumps(self.payload). Our primary issue seems to have been the ALB stickiness cookie.

**Comment by montsamu** [comment]
An idea towards an actual implementation is a parameter 'session_cookie' or similar in the main() lensesio client, which takes as its parameter the name(s) of cookies needed to maintain between login and auth, if they are returned.

**Comment by montsamu** [comment]
Going to need a similar fix here in sql.SQLExec:

    def __init__(self, active_threads, verify_cert=True):
        getEndpoints.__init__(self, "sqlEndpoints")

        self.verify_cert=verify_cert
        self.lenses_sql_query_validation = self.url + self.lensesSQLValidationEndpoint
        self.lenses_exec_sql_endpoint = self.url + self.lensesSQLEndpoint
        self.sql_headers = {
            'Content-Type': 'text/event-stream',
            'Accept': 'text/event-stream',
            'x-kafka-lenses-token': self.token
        }

        self.sql_active_threads = active_threads

**Comment by andmarios** [comment]
Hello @montsamu. I am sorry, but this library has been abandoned for quite some time now and hasn't followed the development of the Lenses REST API.

I will close this issue as we are going to archive the repository. I apologize for the inconvenience both this action and the delay of communication may have caused you.
